# Permalinks
permalink:           /blog/:title/

# Setup
title:               Collegiate Entrepreneurs Organisation, Delhi University
tagline:             CEO DU
description:         We Breathe Startups
footer:              CEO, Delhi University

exclude:             [/psd/]


# Markdown
collections:
  portfolio:
    # output: true
    permalink: /work/:title/
  causes:
    # output: true
    permalink: /work/:title/
  brands:
    # output: true
    permalink: /work/:title/
  hidden:
    output: true
    permalink: /work/:title/
  refrost:
    # output: true
    permalink: /work/:title/


# SASS
sass:
  sass_dir:          _sass
  style:            compressed
  encoding:          utf-8

# Google Analytics
analytics_id:  


# SEO
author:
  name: Shivansh Mehendiratta
  twitter: ceodu
  instagram: ceodu
  youtube: ceodu
  email: ceoinfo.du@gmail.com

defaults:
  - scope:
      path: ""
    values:
      image: /bg.jpeg

profile: /bg.jpg

twitter:
  username: shivansh3121

social:
  name: Shivansh Mehendiratta
  links:
    - https://twitter.com/shivansh3121
    - https://instagram.com/shivansh3121
    - https://youtube.com/c/shivansh3121

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
